In [9]:
#Practical 4
#kalpit thanki
#20627030704
# 1.to add, subtract, multiply, divide arguments element-wise
import numpy as np
a2074=np.array([1,2,3,4,5,6])

In [10]:
print("Array before adding:",a2074)

Array before adding: [1 2 3 4 5 6]


In [11]:
b2074=np.add(a2074,2)

In [12]:
print(b2074)

[3 4 5 6 7 8]


In [13]:
c2074=np.subtract(b2074,0.5)
print(c2074)

[2.5 3.5 4.5 5.5 6.5 7.5]


In [14]:
d2074=np.multiply(c2074,1.5)
print(d2074)

[ 3.75  5.25  6.75  8.25  9.75 11.25]


In [15]:
e2074=np.divide(d2074,1.5)
print(e2074)

[2.5 3.5 4.5 5.5 6.5 7.5]


In [16]:
#2.to round elements of the array to the nearest integer
print(np.round([1.2,.3,1.9]))

[1. 0. 2.]


In [17]:
print(np.around([1.4,1.9]))

[1. 2.]


In [18]:
print(np.rint([1.2,1.9]))

[1. 2.]


In [19]:
#3.to calculate mean across dimension, in a 2D numpy array
f7074=np.array(([10,10],[20,30]))
print(f7074)

[[10 10]
 [20 30]]


In [20]:
print(np.mean(f7074,axis=1))
print(np.mean(f7074,axis=0))

[10. 25.]
[15. 20.]


In [21]:
#4.to calculate the difference between neighboring elements, element-wise of a given array
g7074=np.array([1,8,8,15,19])
print(np.diff(g7074))

[7 0 7 4]


In [22]:
h7074=np.array([1,3,3,9,11,18,18,21,21,28,28,35,39])
print(np.diff(h7074))

[2 0 6 2 7 0 3 0 7 0 7 4]


In [23]:
i7074=np.array([1,10,14,16,25,29,34,39,47,50,50])
k=print(np.diff(i7074))

[9 4 2 9 4 5 5 8 3 0]


In [24]:
j7074=np.array([1,1,4,12,17,22,26,35,37,41,50])
print(np.diff(j7074))

[0 3 8 5 5 4 9 2 4 9]


In [29]:
k=np.diff(i7074)
print(k)

[9 4 2 9 4 5 5 8 3 0]


In [30]:
print(np.flip(k))

[0 3 8 5 5 4 9 2 4 9]
